name: Workflow Testing

concurrency:
    group: compressed-size-${{ github.ref }}

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        name: Test job
        runs-on: ubuntu-latest

        steps:
            - name: Use desired version of NodeJS
              run: |
                echo "Test job starts"
                sleep 1m
                echo "Test job continues"
                sleep 1m
                echo "Test job finishes"
