name: Workflow Testing done final

concurrency:
    group: compressed-size-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        name: Test job
        runs-on: ubuntu-latest

        steps:
            - name: Use desired version of NodeJS in this action
              run: |
                echo ${{ github.ref }}
                sleep 1m
                echo "Test job continues"
                sleep 1m
                echo "Test job finishes"
